class MVS_Pack_Base extends Clothing {};
class MVS_Assault_Pack_Tan extends MVS_Pack_Base{};
class MVS_Assault_Pack_OD extends MVS_Pack_Base{};
class MVS_Assault_Pack_ERDL extends MVS_Pack_Base{};
class MVS_Assault_Pack_Black extends MVS_Pack_Base{};
class MVS_Assault_Pack_Snow extends MVS_Pack_Base{};
class MVS_Assault_Pack_Multicam extends MVS_Pack_Base{};
class MVS_Assault_Pack_Multicam_Tropic extends MVS_Pack_Base{};
class MVS_Assault_Pack_Multicam_Black extends MVS_Pack_Base{};
class MVS_SlingPack_Base extends MVS_Pack_Base{};
class MVS_SlingPack_OD extends MVS_Pack_Base{};
class MVS_SlingPack_Tan extends MVS_Pack_Base{};
class MVS_SlingPack_Black extends MVS_Pack_Base{};
class MVS_SlingPack_Multicam extends MVS_Pack_Base{};
class MVS_SlingPack_Multicam_Black extends MVS_Pack_Base{};
class MVS_SlingPack_Multicam_Tropic extends MVS_Pack_Base{};
class MVS_SlingPack_ERDL extends MVS_Pack_Base{};
class MVS_SlingPack_Snow extends MVS_Pack_Base{};
class MVS_Compact_Base extends MVS_Pack_Base{};
class MVS_Compact_1_OD extends MVS_Pack_Base{};
class MVS_Compact_1_Tan extends MVS_Pack_Base{};
class MVS_Compact_1_Black extends MVS_Pack_Base{};
class MVS_Compact_1_ERDL extends MVS_Pack_Base{};
class MVS_Compact_1_Snow extends MVS_Pack_Base{};
class MVS_Compact_1_Multicam extends MVS_Pack_Base{};
class MVS_Compact_1_Multicam_Tropic extends MVS_Pack_Base{};
class MVS_Compact_1_Multicam_Black extends MVS_Pack_Base{};
class MVS_Compact_Base_2 extends MVS_Pack_Base{};
class MVS_Compact_2_OD extends MVS_Pack_Base{};
class MVS_Compact_2_Tan extends MVS_Pack_Base{};
class MVS_Compact_2_Black extends MVS_Pack_Base{};
class MVS_Compact_2_ERDL extends MVS_Pack_Base{};
class MVS_Compact_2_Snow extends MVS_Pack_Base{};
class MVS_Compact_2_Multicam extends MVS_Pack_Base{};
class MVS_Compact_2_Multicam_Tropic extends MVS_Pack_Base{};
class MVS_Compact_2_Multicam_Black extends MVS_Pack_Base{};
class MVS_Pack_OD extends MVS_Pack_Base{};
class MVS_Pack_ERDL extends MVS_Pack_Base{};
class MVS_Pack_Tan extends MVS_Pack_Base{};
class MVS_Pack_Black extends MVS_Pack_Base{};
class MVS_Pack_Snow extends MVS_Pack_Base{};
class MVS_Pack_Multicam extends MVS_Pack_Base{};
class MVS_Pack_Multicam_Tropic extends MVS_Pack_Base{};
class MVS_Pack_Multicam_Black extends MVS_Pack_Base{};

class MVS_Rucksack_Base extends Clothing {};
class MVS_Rucksack_OD extends MVS_Rucksack_Base {};
class MVS_Rucksack_ERDL extends MVS_Rucksack_Base {};
class MVS_Rucksack_Tan extends MVS_Rucksack_Base {};
class MVS_Rucksack_Black extends MVS_Rucksack_Base {};
class MVS_Rucksack_Snow extends MVS_Rucksack_Base {};
class MVS_Rucksack_Multicam extends MVS_Rucksack_Base {};
class MVS_Rucksack_Multicam_Tropic extends MVS_Rucksack_Base {};
class MVS_Rucksack_Multicam_Black extends MVS_Rucksack_Base {};